[package]
name = "jpg-png"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.8.2"
image = "0.25.1"

[profile.release]
# Do not open a console when the program is run
codegen-units = 1
opt-level = 'z'
lto = true
panic = 'abort'
